// default package
// Generated 2017-3-9 16:31:56 by Hibernate Tools 3.5.0.Final
package edu.housesearcher.crawler.entity;
/**
 * AgentWatchTimes generated by hbm2java
 */
public class AgentWatchTimes implements java.io.Serializable {

    private Integer dataId;
    private String AHref;
    private String HHref;
    private String watchTimes;
    private String createTime;

    public AgentWatchTimes() {
    }

    public AgentWatchTimes(String AHref, String HHref, String watchTimes, String createTime) {
	this.AHref = AHref;
	this.HHref = HHref;
	this.watchTimes = watchTimes;
	this.createTime = createTime;
    }

    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    public String getAHref() {
	return this.AHref;
    }

    public void setAHref(String AHref) {
	this.AHref = AHref;
    }

    public String getHHref() {
	return this.HHref;
    }

    public void setHHref(String HHref) {
	this.HHref = HHref;
    }

    public String getWatchTimes() {
	return this.watchTimes;
    }

    public void setWatchTimes(String watchTimes) {
	this.watchTimes = watchTimes;
    }

    public String getCreateTime() {
	return this.createTime;
    }

    public void setCreateTime(String createTime) {
	this.createTime = createTime;
    }

}
