// default package
// Generated 2017-3-9 16:31:56 by Hibernate Tools 3.5.0.Final
package edu.housesearcher.crawler.entity;
/**
 * AgentManaScope generated by hbm2java
 */
public class AgentManaScope implements java.io.Serializable {

    private Integer dataId;
    private String AHref;
    private String CHref;
    private String createTime;

    public AgentManaScope() {
    }

    public AgentManaScope(String AHref, String CHref, String createTime) {
	this.AHref = AHref;
	this.CHref = CHref;
	this.createTime = createTime;
    }

    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    public String getAHref() {
	return this.AHref;
    }

    public void setAHref(String AHref) {
	this.AHref = AHref;
    }

    public String getCHref() {
	return this.CHref;
    }

    public void setCHref(String CHref) {
	this.CHref = CHref;
    }

    public String getCreateTime() {
	return this.createTime;
    }

    public void setCreateTime(String createTime) {
	this.createTime = createTime;
    }

}
