// default package
// Generated 2017-3-12 20:48:45 by Hibernate Tools 3.5.0.Final
package edu.housesearcher.crawler.entity;
/**
 * CrawlerCfg generated by hbm2java
 */
public class CrawlerCfg implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer dataId;
    private String website;
    private String crawler;
    private String enabled;
    private String lastExeTime;
    private String createTime;

    public CrawlerCfg() {
    }

    public CrawlerCfg(String website, String crawler, String enabled, String lastExeTime, String createTime) {
	this.website = website;
	this.crawler = crawler;
	this.enabled = enabled;
	this.lastExeTime = lastExeTime;
	this.createTime = createTime;
    }

    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    public String getWebsite() {
	return this.website;
    }

    public void setWebsite(String website) {
	this.website = website;
    }

    public String getCrawler() {
	return this.crawler;
    }

    public void setCrawler(String crawler) {
	this.crawler = crawler;
    }

    public String getEnabled() {
	return this.enabled;
    }

    public void setEnabled(String enabled) {
	this.enabled = enabled;
    }

    public String getLastExeTime() {
	return this.lastExeTime;
    }

    public void setLastExeTime(String lastExeTime) {
	this.lastExeTime = lastExeTime;
    }

    public String getCreateTime() {
	return this.createTime;
    }

    public void setCreateTime(String createTime) {
	this.createTime = createTime;
    }

}
