// default package
// Generated 2017-3-3 23:23:39 by Hibernate Tools 5.1.0.Alpha1
package edu.housesearcher.crawler.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EntAgent generated by hbm2java
 */
@Entity
@Table(name = "ent_agent", catalog = "housesearcher", uniqueConstraints = @UniqueConstraint(columnNames = "H_HREF"))
public class EntAgent implements java.io.Serializable {

    private Integer dataId;
    private String HHref;
    private String name;
    private String phone;
    private String CHref;

    public EntAgent() {
    }

    public EntAgent(String HHref, String name, String phone, String CHref) {
	this.HHref = HHref;
	this.name = name;
	this.phone = phone;
	this.CHref = CHref;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "DATA_ID", unique = true, nullable = false)
    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    @Column(name = "H_HREF", unique = true, length = 100)
    public String getHHref() {
	return this.HHref;
    }

    public void setHHref(String HHref) {
	this.HHref = HHref;
    }

    @Column(name = "NAME", length = 30)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "PHONE", length = 20)
    public String getPhone() {
	return this.phone;
    }

    public void setPhone(String phone) {
	this.phone = phone;
    }

    @Column(name = "C_HREF", length = 100)
    public String getCHref() {
	return this.CHref;
    }

    public void setCHref(String CHref) {
	this.CHref = CHref;
    }

}
