// default package
// Generated 2017-3-3 23:23:39 by Hibernate Tools 5.1.0.Alpha1
package edu.housesearcher.crawler.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EntCommunity generated by hbm2java
 */
@Entity
@Table(name = "ent_community", catalog = "housesearcher", uniqueConstraints = @UniqueConstraint(columnNames = "A_HREF"))
public class EntCommunity implements java.io.Serializable {

    private Integer dataId;
    private String AHref;
    private String CLocation;
    private Character coord;

    public EntCommunity() {
    }

    public EntCommunity(String AHref, String CLocation, Character coord) {
	this.AHref = AHref;
	this.CLocation = CLocation;
	this.coord = coord;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "DATA_ID", unique = true, nullable = false)
    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    @Column(name = "A_HREF", unique = true, length = 100)
    public String getAHref() {
	return this.AHref;
    }

    public void setAHref(String AHref) {
	this.AHref = AHref;
    }

    @Column(name = "c_location", length = 100)
    public String getCLocation() {
	return this.CLocation;
    }

    public void setCLocation(String CLocation) {
	this.CLocation = CLocation;
    }

    @Column(name = "coord", length = 0)
    public Character getCoord() {
	return this.coord;
    }

    public void setCoord(Character coord) {
	this.coord = coord;
    }

}
