// default package
// Generated 2017-3-9 16:31:56 by Hibernate Tools 3.5.0.Final
package edu.housesearcher.crawler.entity;
/**
 * EntCommunity generated by hbm2java
 */
public class EntCommunity implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer dataId;
    private String CHref;
    private String CLocation;
    private String coord;
    private String isGetMsg;
    private String createTime;

    public EntCommunity() {
    }

    public EntCommunity(String CHref, String CLocation, String coord, String isGetMsg, String createTime) {
	this.CHref = CHref;
	this.CLocation = CLocation;
	this.coord = coord;
	this.isGetMsg = isGetMsg;
	this.createTime = createTime;
    }

    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    public String getCHref() {
	return this.CHref;
    }

    public void setCHref(String CHref) {
	this.CHref = CHref;
    }

    public String getCLocation() {
	return this.CLocation;
    }

    public void setCLocation(String CLocation) {
	this.CLocation = CLocation;
    }

    public String getCoord() {
	return this.coord;
    }

    public void setCoord(String coord) {
	this.coord = coord;
    }

    public String getIsGetMsg() {
	return this.isGetMsg;
    }

    public void setIsGetMsg(String isGetMsg) {
	this.isGetMsg = isGetMsg;
    }

    public String getCreateTime() {
	return this.createTime;
    }

    public void setCreateTime(String createTime) {
	this.createTime = createTime;
    }

}
