// default package
// Generated 2017-3-3 23:23:39 by Hibernate Tools 5.1.0.Alpha1
package edu.housesearcher.crawler.entity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EntHouse generated by hbm2java
 */
@Entity
@Table(name = "ent_house", catalog = "housesearcher", uniqueConstraints = @UniqueConstraint(columnNames = "H_HREF"))
public class EntHouse implements java.io.Serializable {

    private Integer dataId;
    private String HHref;
    private Date pubDate;
    private Character HType;
    private Integer HLevel;
    private String HOrientation;
    private String CHref;
    private String CLocation;
    private Integer agentId;

    public EntHouse() {
    }

    public EntHouse(String HHref, Date pubDate, Character HType, Integer HLevel, String HOrientation, String CHref,
	    String CLocation, Integer agentId) {
	this.HHref = HHref;
	this.pubDate = pubDate;
	this.HType = HType;
	this.HLevel = HLevel;
	this.HOrientation = HOrientation;
	this.CHref = CHref;
	this.CLocation = CLocation;
	this.agentId = agentId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "data_id", unique = true, nullable = false)
    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    @Column(name = "H_HREF", unique = true, length = 100)
    public String getHHref() {
	return this.HHref;
    }

    public void setHHref(String HHref) {
	this.HHref = HHref;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "PUB_DATE", length = 10)
    public Date getPubDate() {
	return this.pubDate;
    }

    public void setPubDate(Date pubDate) {
	this.pubDate = pubDate;
    }

    @Column(name = "h_type", length = 0)
    public Character getHType() {
	return this.HType;
    }

    public void setHType(Character HType) {
	this.HType = HType;
    }

    @Column(name = "h_level")
    public Integer getHLevel() {
	return this.HLevel;
    }

    public void setHLevel(Integer HLevel) {
	this.HLevel = HLevel;
    }

    @Column(name = "h_orientation", length = 2)
    public String getHOrientation() {
	return this.HOrientation;
    }

    public void setHOrientation(String HOrientation) {
	this.HOrientation = HOrientation;
    }

    @Column(name = "c_href", length = 100)
    public String getCHref() {
	return this.CHref;
    }

    public void setCHref(String CHref) {
	this.CHref = CHref;
    }

    @Column(name = "c_location", length = 100)
    public String getCLocation() {
	return this.CLocation;
    }

    public void setCLocation(String CLocation) {
	this.CLocation = CLocation;
    }

    @Column(name = "agent_id")
    public Integer getAgentId() {
	return this.agentId;
    }

    public void setAgentId(Integer agentId) {
	this.agentId = agentId;
    }

}
