// default package
// Generated 2017-4-16 11:28:37 by Hibernate Tools 3.5.0.Final
package edu.housesearcher.crawler.entity;
/**
 * EntHouse generated by hbm2java
 */
public class EntHouse implements java.io.Serializable {

    private Integer dataId;
    private String HHref;
    private String HTitle;
    private String HTags;
    private String pubDate;
    private String area;
    private String price;
    private String HCell;
    private String HRoom;
    private String HLevel;
    private String HOrientation;
    private String imgHref;
    private String CHref;
    private String AHref;
    private String isGetMsg;
    private String createTime;

    public EntHouse() {
    }

    public EntHouse(String HHref, String HTitle, String HTags, String pubDate, String area, String price, String HCell,
	    String HRoom, String HLevel, String HOrientation, String imgHref, String CHref, String AHref,
	    String isGetMsg, String createTime) {
	this.HHref = HHref;
	this.HTitle = HTitle;
	this.HTags = HTags;
	this.pubDate = pubDate;
	this.area = area;
	this.price = price;
	this.HCell = HCell;
	this.HRoom = HRoom;
	this.HLevel = HLevel;
	this.HOrientation = HOrientation;
	this.imgHref = imgHref;
	this.CHref = CHref;
	this.AHref = AHref;
	this.isGetMsg = isGetMsg;
	this.createTime = createTime;
    }

    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    public String getHHref() {
	return this.HHref;
    }

    public void setHHref(String HHref) {
	this.HHref = HHref;
    }

    public String getHTitle() {
	return this.HTitle;
    }

    public void setHTitle(String HTitle) {
	this.HTitle = HTitle;
    }

    public String getHTags() {
	return this.HTags;
    }

    public void setHTags(String HTags) {
	this.HTags = HTags;
    }

    public String getPubDate() {
	return this.pubDate;
    }

    public void setPubDate(String pubDate) {
	this.pubDate = pubDate;
    }

    public String getArea() {
	return this.area;
    }

    public void setArea(String area) {
	this.area = area;
    }

    public String getPrice() {
	return this.price;
    }

    public void setPrice(String price) {
	this.price = price;
    }

    public String getHCell() {
	return this.HCell;
    }

    public void setHCell(String HCell) {
	this.HCell = HCell;
    }

    public String getHRoom() {
	return this.HRoom;
    }

    public void setHRoom(String HRoom) {
	this.HRoom = HRoom;
    }

    public String getHLevel() {
	return this.HLevel;
    }

    public void setHLevel(String HLevel) {
	this.HLevel = HLevel;
    }

    public String getHOrientation() {
	return this.HOrientation;
    }

    public void setHOrientation(String HOrientation) {
	this.HOrientation = HOrientation;
    }

    public String getImgHref() {
	return this.imgHref;
    }

    public void setImgHref(String imgHref) {
	this.imgHref = imgHref;
    }

    public String getCHref() {
	return this.CHref;
    }

    public void setCHref(String CHref) {
	this.CHref = CHref;
    }

    public String getAHref() {
	return this.AHref;
    }

    public void setAHref(String AHref) {
	this.AHref = AHref;
    }

    public String getIsGetMsg() {
	return this.isGetMsg;
    }

    public void setIsGetMsg(String isGetMsg) {
	this.isGetMsg = isGetMsg;
    }

    public String getCreateTime() {
	return this.createTime;
    }

    public void setCreateTime(String createTime) {
	this.createTime = createTime;
    }

}
