// default package
// Generated 2017-3-9 16:31:56 by Hibernate Tools 3.5.0.Final
package edu.housesearcher.crawler.entity;
/**
 * EntHouse generated by hbm2java
 */
public class EntHouse implements java.io.Serializable {

    private Integer dataId;
    private String HHref;
    private String pubDate;
    private String area;
    private String price;
    private String HType;
    private String HLevel;
    private String HOrientation;
    private String CHref;
    private String AHref;
    private String isGetMsg;
    private String createTime;

    public EntHouse() {
    }

    public EntHouse(String HHref, String pubDate, String area, String price, String HType, String HLevel,
	    String HOrientation, String CHref, String AHref, String isGetMsg, String createTime) {
	this.HHref = HHref;
	this.pubDate = pubDate;
	this.area = area;
	this.price = price;
	this.HType = HType;
	this.HLevel = HLevel;
	this.HOrientation = HOrientation;
	this.CHref = CHref;
	this.AHref = AHref;
	this.isGetMsg = isGetMsg;
	this.createTime = createTime;
    }

    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    public String getHHref() {
	return this.HHref;
    }

    public void setHHref(String HHref) {
	this.HHref = HHref;
    }

    public String getPubDate() {
	return this.pubDate;
    }

    public void setPubDate(String pubDate) {
	this.pubDate = pubDate;
    }

    public String getArea() {
	return this.area;
    }

    public void setArea(String area) {
	this.area = area;
    }

    public String getPrice() {
	return this.price;
    }

    public void setPrice(String price) {
	this.price = price;
    }

    public String getHType() {
	return this.HType;
    }

    public void setHType(String HType) {
	this.HType = HType;
    }

    public String getHLevel() {
	return this.HLevel;
    }

    public void setHLevel(String HLevel) {
	this.HLevel = HLevel;
    }

    public String getHOrientation() {
	return this.HOrientation;
    }

    public void setHOrientation(String HOrientation) {
	this.HOrientation = HOrientation;
    }

    public String getCHref() {
	return this.CHref;
    }

    public void setCHref(String CHref) {
	this.CHref = CHref;
    }

    public String getAHref() {
	return this.AHref;
    }

    public void setAHref(String AHref) {
	this.AHref = AHref;
    }

    public String getIsGetMsg() {
	return this.isGetMsg;
    }

    public void setIsGetMsg(String isGetMsg) {
	this.isGetMsg = isGetMsg;
    }

    public String getCreateTime() {
	return this.createTime;
    }

    public void setCreateTime(String createTime) {
	this.createTime = createTime;
    }

}
