// default package
// Generated 2017-4-13 22:25:45 by Hibernate Tools 3.5.0.Final
package edu.housesearcher.crawler.entity;
/**
 * EntUser generated by hbm2java
 */
public class EntUser implements java.io.Serializable {

    private String phone;
    private String pwd;

    public EntUser() {
    }

    public EntUser(String phone) {
	this.phone = phone;
    }

    public EntUser(String phone, String pwd) {
	this.phone = phone;
	this.pwd = pwd;
    }

    public String getPhone() {
	return this.phone;
    }

    public void setPhone(String phone) {
	this.phone = phone;
    }

    public String getPwd() {
	return this.pwd;
    }

    public void setPwd(String pwd) {
	this.pwd = pwd;
    }

}
