// default package
// Generated 2017-4-17 15:12:26 by Hibernate Tools 3.5.0.Final
package edu.housesearcher.crawler.entity;
/**
 * EntUser generated by hbm2java
 */
public class EntUser implements java.io.Serializable {

    private Integer dataId;
    private String telephone;
    private String firstName;
    private String nickName;
    private String pwd;
    private String createTime;

    public EntUser() {
    }

    public EntUser(String pwd) {
	this.pwd = pwd;
    }

    public EntUser(String telephone, String firstName, String nickName, String pwd, String createTime) {
	this.telephone = telephone;
	this.firstName = firstName;
	this.nickName = nickName;
	this.pwd = pwd;
	this.createTime = createTime;
    }

    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    public String getTelephone() {
	return this.telephone;
    }

    public void setTelephone(String telephone) {
	this.telephone = telephone;
    }

    public String getFirstName() {
	return this.firstName;
    }

    public void setFirstName(String firstName) {
	this.firstName = firstName;
    }

    public String getNickName() {
	return this.nickName;
    }

    public void setNickName(String nickName) {
	this.nickName = nickName;
    }

    public String getPwd() {
	return this.pwd;
    }

    public void setPwd(String pwd) {
	this.pwd = pwd;
    }

    public String getCreateTime() {
	return this.createTime;
    }

    public void setCreateTime(String createTime) {
	this.createTime = createTime;
    }

}
