// default package
// Generated 2017-3-11 9:42:55 by Hibernate Tools 3.5.0.Final
package edu.housesearcher.crawler.entity;

/**
 * StatusValue generated by hbm2java
 */
public class StatusValue implements java.io.Serializable {

    /**
     * 
     */
    private String statusKey;
    private String statusValue;
    private String enabled;
    private String createTime;

    public StatusValue() {
    }

    public StatusValue(String statusKey) {
	this.statusKey = statusKey;
    }

    public StatusValue(String statusKey, String statusValue, String enabled, String createTime) {
	this.statusKey = statusKey;
	this.statusValue = statusValue;
	this.enabled = enabled;
	this.createTime = createTime;
    }

    public String getStatusKey() {
	return this.statusKey;
    }

    public void setStatusKey(String statusKey) {
	this.statusKey = statusKey;
    }

    public String getStatusValue() {
	return this.statusValue;
    }

    public void setStatusValue(String statusValue) {
	this.statusValue = statusValue;
    }

    public String getEnabled() {
	return this.enabled;
    }

    public void setEnabled(String enabled) {
	this.enabled = enabled;
    }

    public String getCreateTime() {
	return this.createTime;
    }

    public void setCreateTime(String createTime) {
	this.createTime = createTime;
    }

}
