// default package
// Generated 2017-4-17 15:12:26 by Hibernate Tools 3.5.0.Final
package edu.housesearcher.crawler.entity;
/**
 * UserCollectHouse generated by hbm2java
 */
public class UserCollectHouse implements java.io.Serializable {

    private Integer dataId;
    private String telephone;
    private String HHref;
    private String createTime;

    public UserCollectHouse() {
    }

    public UserCollectHouse(String telephone, String HHref, String createTime) {
	this.telephone = telephone;
	this.HHref = HHref;
	this.createTime = createTime;
    }

    public Integer getDataId() {
	return this.dataId;
    }

    public void setDataId(Integer dataId) {
	this.dataId = dataId;
    }

    public String getTelephone() {
	return this.telephone;
    }

    public void setTelephone(String telephone) {
	this.telephone = telephone;
    }

    public String getHHref() {
	return this.HHref;
    }

    public void setHHref(String HHref) {
	this.HHref = HHref;
    }

    public String getCreateTime() {
	return this.createTime;
    }

    public void setCreateTime(String createTime) {
	this.createTime = createTime;
    }

}
